# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies for CipherChallenge
      run: dotnet restore
      working-directory: CipherChallenge/
      
    - name: Restore dependencies for CipherChallenge.tests
      run: dotnet restore
      working-directory: CipherChallenge.tests/
      
    - name: Build CipherChallenge
      run: dotnet build --no-restore
      working-directory: CipherChallenge/
      
    - name: Run CipherChallenge.tests
      run: dotnet test --no-restore
      working-directory: CipherChallenge.tests/
